services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  flask-app:
    build:
      context: ./flask-htmx
    container_name: flask-app
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb

  express-server:
    build:
      context: ./game-server
    container_name: express-server
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      - flask-app
      - express-server
    ports:
      - "80:80"  # Expose only Nginx on port 80

volumes:
  mongo-data:

