apiVersion: apps/v1
kind: Deployment
metadata:
  name: rts-game-flask-app
  namespace: default
  labels:
    app: rts-game-flask-app
spec:
  selector:
    matchLabels:
      app: rts-game-flask-app
  template:
    metadata:
      labels:
        app: rts-game-flask-app
    spec:
      containers:
        - name: rts-game-flask-app
          image: mmarci96/rts-game-flask-app:latest
          env:
            - name: MONGO_USER
              valueFrom: 
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-password
            - name: MONGO_URI
              value: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@rts-game-mongodb:27017/rts-game-db"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"        
          readinessProbe:
            httpGet:
              path: /home/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /home/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
---

apiVersion: v1
kind: Service
metadata:
  name: rts-game-flask-app
  namespace: default
spec:
  selector:
    app: rts-game-flask-app  # Must match the Flask app pod labels
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000  
  type: ClusterIP  

