# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  flask-app
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 390403884602.dkr.ecr.eu-north-1.amazonaws.com/rts-game-flask-app:latest
          imagePullPolicy: IfNotPresent
          resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
spec:
  selector:
    app: flask-app
  type: ClusterIP
  ports:
  - name: flask-app
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
---

