
# RTS Game Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rts-game-client
  namespace: default
  labels:
    app: rts-game-client
spec:
  selector:
    matchLabels:
      app: rts-game-client
  template:
    metadata:
      labels:
        app: rts-game-client
    spec:
      containers:
        - name: rts-game-client
          image: mmarci96/my-rts-game-client:latest 
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---

# Nginx Service
apiVersion: v1
kind: Service
metadata:
  name: rts-game-client
  namespace: default
spec:
  selector:
    app: rts-game-client    # Match label of rts-game-client Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

