# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rts-game-client
  namespace: default
  labels:
    app: rts-game-client
spec:
  selector:
    matchLabels:
      app: rts-game-client
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  rts-game-client
      labels:
        app: rts-game-client
    spec:
      containers:
      - name: rts-game-client
        image: myjob:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: rts-game-client
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

